version: '3'

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - amrit
    restart: always

  backend:
    image: "subediamrit22/wanderlust_backend:backend1"
    container_name: "backend"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27018/wanderlust
      - CORS_ORIGIN=http://44.206.143.8:8010
      - FRONTEND_URL=http://44.206.143.8:8010
    ports:
      - "5000:5000"
    networks:
      - amrit
    depends_on:
      - mongodb
    restart: always

  frontend:
    image: "subediamrit22/wanderlust_frontend:frontend1"
    container_name: "frontend"
    environment:
      - VITE_API_PATH=http://44.206.143.8:5000
    ports:
      - "8010:8010"
    networks:
      - amrit
    restart: always

networks:
  amrit:

