version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - mydata:/data/db
    networks:
      - amrit

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb2:27017/wanderlust
      - CORS_ORIGIN=http://44.206.143.8:8010
      - FRONTEND_URL=http://44.206.143.8:8010
    ports:
      - "5000:5000"
    restart: always
    networks:
      - amrit

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    environment:
      - VITE_API_PATH=http://44.206.143.8:5000
    ports:
      - "8010:8000"
    restart: always
    networks:
      - amrit

networks:
  amrit:
volumes:
  mydata:
