name: continous Integration

on:
  push:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      _

        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      _ 

        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/
          push: true
          tags: subediamrit22/frontend2:latest

  Backend-build:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      _  
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend/
          push: true
          tags: subediamrit22/backend2:latest

  Deploy-wanderlust:
    name: build
    runs-on:
    steps:
      - name: copy docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml"
          target: /home/ubuntu

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         script: whoami




